### ISSUE TITLE
Storing functions in the store considered an anti-pattern

### ISSUE THREAD

**Issue by markerikson** [luispablo/common-reducers#1]
Generally not a good idea to store non-serializable items in the store.  See http://redux.js.org/docs/FAQ.html#organizing-state-non-serializable.

**Comment by luispablo** [comment]
Thanks for the info! It looked like a code smell, but I couldn't think how to implement it... Any suggestions?

**Comment by markerikson** [comment]
All it's actually doing is checking to see if a given name has a corresponding flag value in the store, right?  In that case, seems like what you really want is to provide "selector" functions instead, alongside the reducers.  See http://redux.js.org/docs/recipes/ComputingDerivedData.html.  (Should also be one of the topics covered in Dan's next set of Redux tutorial videos, which are due out on Egghead in the next few days.)
